site_name: UKnowXChange
repo_url: https://github.com/fbellom/uprrp-knowledge-xfer
theme:
  name: material
  logo: assets/ccom_logo.png
  palette:
    primary: white
    accent: black
  font:
    text: Roboto
    code: Roboto Mono
  feature:
    tabs: true
nav:
  - index.md
  - Overview:
      - About: overview/overview.md
      - Getting Started with Docker: overview/getting_started.md
      - Getting Started with Git: overview/getting_started_with_git.md
  - Demos:
      - NodeJS in Docker: demos/nodeapp.md
      - Go App compile with Multi-Stage Dockerfile: demos/golangapp.md
      - Running several Containers with Docker compose: demos/composeapp.md
plugins:
  - search
