site_name: UKnowXChange
theme:
  name: material
  logo: assets/ccom_logo.png
  palette:
    primary: white
    accent: black
  font:
    text: Roboto
    code: Roboto Mono
  feature:
    tabs: true
nav:
  - Overview:
      - About: overview/overview.md
      - Getting Started with Docker: overview/getting_started.md
  - Demos:
      - NodeJS in Docker: demos/nodeapp.md
      - Go App compile with Multi-Stage Dockerfile: demos/golangapp.md
plugins:
  - search
